### ISSUE TITLE
Complete translation to Spanish inside of Mathspring

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#10]
We need to complete translation to Spanish inside Mathspring.
Because it should be translated by now in full, I consider this a bug.

This involves areas of the Student Progress Page, which are hard-coded right now.

It also involves pop-up boxes at the end of a Topic, when it is mastered, or is moving on to another topic for some reason.

There are several areas:

- Teacher Tools, in the reports in particular (Class Report Card, in SP is Libreta de la Clase)

- Some messages in the Student Progress Page are in English (but they are hard coded).

- A few windows pop-up as you exit a problem set, and they are all in English, hard-coded).

**Comment by IvonArroyo** [comment]
The only issue that I see right now is that when you run MathSpring from mathspring.org, the hints say "Paso1, Paso2" instead of "Step1, Step2"

**Comment by FrankSylvia** [comment]
That is fixed in the Dev/QA version.

On another topic:
My final changes for the 'per Student per Problem' report are pushed to QA
and should be available after tomorrow morning's build. I think we could
merge all the QA changes into Production once that final change is
approved.

I will need to work with Ankit on how that is managed.  Is he still
around?  I haven't heard from him in a while.

As you may have assumed, I'm back home at work. The trip was really
exhausting, and my network access was very poor, and hampered my
productivity. I am ready to pick up the pace now, so please tell me which
issue(s) I should start with.


Thanks for being understanding about my leave,
Frank

**Comment by IvonArroyo** [comment]
Hi Frank, I approve this, ready to close.
Is there a new database in the QA server? I can see data from 10 days ago!
That is great.

------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002
