### ISSUE TITLE
Issues with "H" problems and standards

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#110]
See email from danielle May 12, 2020.
I expect that there is a problem here with accessing high school problems/standards.  High school standards have a grade "H".  At one point we decided we needed a numeric grade for everything and that H would be "9" for all high school. But we could not get rid of the H because "9" is for internal processing and teachers should only see "H" (as "9" is technically wrong, it could be 10,11,12). So there two fields: grade and  gradeAlphaNum, where  for HS prolbems grade is "9", and gradeAlphaNum is "H".  Checking the database the PROBLEM is, that gradeAlphaNum is a property of the problem, not the standard, and this should be changed (the problem should get gradeAlphaNum from its standard, just like it gets its grade from standard--see Issue 108).

**Comment by IvonArroyo** [comment]
The Java code should check if it is an "H" and turn it into 9, as then the grade is used for numerical computations.

**Comment by perspegrity5** [comment]
True Ivon?: we want the teachers to see "H", not "9", because its really a "9-12" standard.  So there are places in the code that need the "9" and other places that need the "H".  Both variations of this "grade' are stored in fields, as noted.

**Comment by IvonArroyo** [comment]
I guess it depends where it is used. If it is for the reports, then the teachers should see "H". However, the grade is used for computation of an estimation of problem difficulty, during MathSpring start-up. In that case, the Java code should turn it into a "9".

**Comment by FrankSylvia** [comment]
I think this issue is resolved.  Can someone confirm using the Dev/QA server?
