### ISSUE TITLE
Teacher can login with email or username

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#118]
Teacher can login with email or username.
If teacher credentials are invalid, remind teacher that they can login with email also.

**Comment by FrankSylvia** [comment]
Can we drop this request?  I think we agreed that email addresses are not unique and thus not appropriate for logging in.

**Comment by IvonArroyo** [comment]
I think it is fine. Drop it.
What we really need is a link to a new page for the 'forgot username'.
------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Please review this sequence and give me some feedback.

**Comment by IvonArroyo** [comment]
Let's close this issue, it doesn't make sense.
