### ISSUE TITLE
Lisa problems with reports

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#119]
How come students on April 22 from class 1587 should have seen only topics 10 and inequalities topic number.

How come did they switch to other topics in the eventlog and studentproblemhistory.

--Ivon

**Comment by FrankSylvia** [comment]
This could be caused by problem #184.  Alsom at the time, probelm groups, and topics were in flux.  I'm not sure we can explain the actual cause of this particular incident at this time.
