### ISSUE TITLE
When MSAdmin authored problems play as examples, choices don't show

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#12]
When problem number #1809 shows as an example inside MathSpring, it does not display the answer choices at all, which leaves half of the problem not displayed.
I wonder if all multiple-choice problems do this also when being shown as examples?

However, when I see it as a practice problem, it does show the answer choices

**Comment by FrankSylvia** [comment]
This issue was fixed in July in one of the ms-spanish-.. branches.

**Comment by IvonArroyo** [comment]
Frank, the problem now is that the answer boxes for short answer do show in the example problems.

So we want: multiple choices to show, but short answer NOT to show.
