### ISSUE TITLE
Sign up for students doesn't work any more

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#121]
Sign up for students doesn't load the list of classes page right now.

The sign up for students page should also have the possibility of entering a class code to establish their class without seeing the full list (optional, if they know it).

--Ivon

**Comment by FrankSylvia** [comment]
This actually does work.  It takes up to several minutes to return with the class selection page.

Needs investigation for why the relay is so long.

**Comment by IvonArroyo** [comment]
Yes, I saw yesterday, let's close this one.
