### ISSUE TITLE
Teacher Tools: Manage Students, create a link for students to login

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#122]
Sign up student page should also have the possibility to enter the class code .

When using MS remotely, the teacher should be able to generate a link that can be emailed to students, which will already have the classID to assign to the student.

This means that, if you just click on the link, it will take you to the Student Sign up page, and populate the class ID field automatically.

This will help when using MS online if teachers are remote, through Google Classroom

**Comment by FrankSylvia** [comment]
1. Sign up student page should also have the possibility to enter the class code .  
Add another field to the page, labeled "Class code (if you know it)".  On submit, if the Class code is there and valid, skip the class list display.  (this will be easy)

2. I don't understand what you mean by "When using MS remotely,  the teacher should be able to generate a link that can be emailed to students."

Is this functionality in Teacher Tools, say in the Manage Students page.

Does the teacher know the student's email address and enter it so Mathspring can send the email.?

Or do you mean to display a link that the teacher can cut and then paste into an email that he/she is creating externally?

The link could be something like: mathspring.org/remoteStudentEntry?classid=1234

Can we discuss in the weekly meeting?

**Comment by FrankSylvia** [comment]
I split this off into a new issue, #144 because it is completed and then rest of this issue has a requres a lot more design discussion.

Sign up student page should also have the possibility to enter the class code .

**Comment by IvonArroyo** [comment]
http://mathspring.org/ms/WoAdmin?action=UserRegistrationStart&var=b&startPage=LoginK12_1&classcode=1608

**Comment by IvonArroyo** [comment]
I tested this but doesn't seem to work:

Today I was testing the distance learning link to create users and I realized that the username that I created for distance learning gave me a blank screen when attempting to log in for the first time (password was the ID of the class).

Then I tried logging in with some of the other users that were already created for this class (in Classroom) and I was not able to log in either.

Please solve ASAP as Erik is trying to shoot some videos.

**Comment by FrankSylvia** [comment]
I tested this issue and it seems to be working correctly.
