### ISSUE TITLE
New Report Per Topic: Student x Problem

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#13]
We should create a new report that, for each topic, has a matrix of students as rows and problems as columns.

Each cell should have a check if they solved correctly, and a cross if incorrect.

Because of the adaptive nature we should have grey crosses and checks for the problems a student has not reached, suggesting we believe they would have gotten those correct or incrorrect, depending on their difficulty.

**Comment by IvonArroyo** [comment]
I will add as a comment that we agreed the report is hard to read, so instead we need an accordion or alike system where we list the first 3 characters such as 6.RP, which upon choosing/expanding, will show all the math problems whose standards start with 6.RP, such as 6.RP.A1 for instance.

**Comment by ankitrgupta1** [comment]
There is some problem with the problems with standards starting with 7.5. @FrankSylvia would it be possible to get together and check it? It is currently throwing some messages on the browser if I search for standard 7.

**Comment by FrankSylvia** [comment]
What class were you using?  I'll take a look at it in the morning.

**Comment by FrankSylvia** [comment]
Hi Ankit,

I remember now that I worked on this issue for 2 days and then put it aside
and forgot to go back to it.

Maybe you could figure out what's going wrong with those few problems.  If
we can't get it, at least we only log it to the console and not show it to
the user.

Frank

**Comment by FrankSylvia** [comment]
I guess I'll take another whack at this.

There is no row in the problem table with the reported standardID. I need
to look at the query to see where it is getting the bad standardID value.

**Comment by FrankSylvia** [comment]
The issue was with problems that have dot character in the name field. The Chart javascript utility does like that, so I replace the dots with "_". This fix will come along in a separate branch.

**Comment by FrankSylvia** [comment]
Gonna close this.  There is a fix to an alert message that was caused by "."s in the problem name breaking the chart.js utilility. This fix is in the pipeline for the next batch of changes.
