### ISSUE TITLE
Report Card: All reports should have a time period query allowed 

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#148]
All reports should have a time period query allowed.

For instance, they should be able to see the Common Core report, just for the last 10 days.

**Comment by WillRebel** [comment]
Common core cluster and student do not have time period query
per student per topic and per student per problem do

**Comment by FrankSylvia** [comment]
Haven't gotten to Common Core yet. Its next on my list. The student report
already has a different slant on looking by date. I wasn't planning to do
that one.
