### ISSUE TITLE
Examples: Short answer shows the answer box

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#15]
I thought we had fixed this, but the worked out examples (short answer) show the answer box  still. This confused children in Argentina who tried to answer and nothing happened.

**Comment by ankitrgupta1** [comment]
Do we have any example problem which could be checked for this issue?

**Comment by FrankSylvia** [comment]
When I tested it, I used Ivon's Spanish class. I chose a high number
student, e.g. alumnocordoba22.  Then I answered the survey to get to the
problems and eventually I got to a short answer example problem.

**Comment by IvonArroyo** [comment]
Ankit,

I just checked that if you login as guest, and you choose the topic "Current
Topic: Measurement And Data - Review" from the progress page,  the first
problem should be short answer.

Standards: 5.MD.1

------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Tested in Production. Working fine.
