### ISSUE TITLE
Teacher Activity Log: Need a password so that not all teachers access this

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#153]
Hi Frank,

We need a password, it could be when the Teacher Activity Log launches.
This password could be stored in globalsettings.

You would have to create a new field there I guess... I don't like how this table is configured.
It should say: attribute/value, and allow to specify different possible values and attributes that we might need to speciify.

For insttance, the email to retrieve for lost teacher credentials (issue #135). We talked about this,  that you should be able to specify an email for the teachers to let us know they cannot log in any more or alike.

You might be better off creating a new table for  global settings.

**Comment by ankitrgupta1** [comment]
@IvonArroyo Removed the sesnsitive info

**Comment by FrankSylvia** [comment]
FYI, I already have a working solution for issue #135.

I added a getString(columnName) method for globalsettings.  

I interpreted from the original request that an adminstrative tasks for this data would be manual., e.g. changing an email address, but it may be useful to do it programmatically.

It would be easy to create additional methods that would be useful such as:
insertString(columName, content, encrypt?)
setString(columName, content, encrypt?)
getString(columnName, decrypt?)

**Comment by perspegrity5** [comment]
Looks great Frank, re your questions I will leave it up to the programming team.  Its often really useful to proceduralize or abstract data, so I'd say go for it. 

On a similar note we keep adjusting the allowable valued for the problem STATUS field.  From our recent conversations we will be adding some new status categories in the next month.  There are probably decisions all over the code for things like  "if status == ('ready' or 'testable' or 'in-process')" which will perpetually have to be tweaked whenever we add a new status value. I think its worth doing data proceduralization here as well.  For instance a function could be "status_is_showable" that is ('ready' or 'testable' or 'in-process'); and another status_OK_for_student that is just 'ready'.  You could come up with whatever system makes sense for you.  What do you think?

best, Tom
