### ISSUE TITLE
Adding UNITS to MS problems

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#158]
Adding units to (some) MS problems.  First task is to implement in MSAdmin, then in MS.

Basic strategy:  Units is always a multiple choice, we don't have them type the units in (too many variations are possible). We basically force students to enter the correct units before the problem right/wrong is evaluated (this greatly simplifies the permutations). When they press DONE for the problem, before the problem answer is evaluated, check the units. If its wrong say "Your units are incorrect—first lest get the units right. Please try another choice."  That is we don't call problems wrong if they have incorrect units, we just force them to change the units until they get it correct.  When the units are correct, we evaluate the problem in the usual way. 

Details.  
[This issue is copied to the [MSAdmin repo as issue #26](https://github.com/center-for-knowledge-communication/mathspring-admin/issues/26). Comments for MSAdmin and database aspects of the implementation should go there.]

1. Database: Add fields to the problem table:  unitsChoices, unitsAnswer, unitsFeedback, and unitsUse.  UnitsChoices is a string with comma-separated values.  unitsAnswer is the index (integer) for which is correct. unitsUse gives a fixed choice of: [no_units (default), show_units, multi_choice_units].  The event and studentProblemHistory tables may need to have a field added for units.  But we can skip this for now.  unitsFeedback to give helpful message if they get the units wrong.  (First pass is one hint, future may move to a delimited list (common or json) of hints.)

2. The authoring tool includes fields for "Units" (type in),  "Units Choices" (type in),  "UnitsFeedback," and "Units Usage" (dropdown).  The atool raises an error or warning if the questionType and MultipleChoice are incompatible (i.e. don't make sense), e.g.: units_use = "show_units" only makes sense for short-answer questions. If we include units_feedback, add that text to problem  authoring (note, like all content text items, it gets processed for HTML markup, codecods, etc. before rendering). 

3. MS Problem renderer modifications: 
- units_use = no_units:  do nothing
- units_use =  show units: for shortAnswer questions, show the units after the text entry box.  For other question types, ignore the units.
- units_use = multi_choice, for both shortAnswer and multiChoice question types. drop-down menu to the right of the answer.  Default value says "Please choose the units"

Answer evaluation and feedback: (i.e. when student says Done with problem)

-  When a units is required (text or multi-choice) and the user does not enter or select the units, Add a big red message above the Units saying "Please enter units for your answer"
- If both the units and answer are correct the problem is correct and proceed. 
- See my note above RE: if the units are wrong, forcing the student to try again until they get it correct. Retrying to get the units correct does not count in "number of attempts."  If we include units_feedback, then that is also shown each time they choose wrong units and say DONE.

Note for authors:
- Units choices must include one and only on correct answer. Incorrect answers should be common distractors or wrong answers. Note that cm^2 and ft^2 can't both be choices because an area can be expressed in either units.  But "cm" and "cm^3" are good distractors for the correct answer of "cm^2"

[Note, I may have some details wrong here, e.g. "MultipleChoice" answer type may be called multi_choice or mchoice in the system---check the code.]

**Comment by IvonArroyo** [comment]
Tom, can you please create a copy of this issue in the MSAdmin github please?

**Comment by IvonArroyo** [comment]
Let's make this our next priority! I am bumping it up to "Super High Priority"

**Comment by IvonArroyo** [comment]
Frank and Boming need to talk to understand where the units are stored.

**Comment by IvonArroyo** [comment]
UNITS are to be placed next to the short answer box.

**Comment by perspegrity5** [comment]
I added units to short-answer problems 2343, 2432, and 2330.  The units don't show up in any of them in Mathspring. I had thought that database updates took effect automatically, but if that is not the case that would explain it. 

Also, 2343 did not show up at all--blank problem space. Not sure why.

**Comment by perspegrity5** [comment]
still waiting for resolution of the above testing problem...
