### ISSUE TITLE
Bug in editing profile.

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#170]
If i want to access my profile the only way I can do this is when I am on the home screen. In other words if I am in a class and try to click on my profile to access it from it here it doesn't work.  I have to go back to the home and then access it.

**Comment by FrankSylvia** [comment]
Hi Ivon,

The teacher profile page was implemented within the TeacherToolsMain.jsp.  There is actually no link to get to it, as it is presented using .hide() and .show() of it's <div> tag.  

How likely would it be that a teacher would be working with the details of a class and want to jump to a page to change his/her profile?

It would be a significant effort to move it to be it's own link.  And if it were to be made accessible from classDetail.jsp, there would be no easy way to return to whatever you were doing in classDetails.jsp.  It could be done be replicating the TeacherToolsMain logic for clicking a class on the home page.

I would like to propose removing the profile link from the classDetails page.  If user's find it inconvenient we could addresses it when crunch time is over.

WHat do you think?

Frank

**Comment by FrankSylvia** [comment]
Removed 'Progile' option from Class Details page
