### ISSUE TITLE
Videos that show upon request: Algorithm is incorrect

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#192]
This is the same as the examples. When one clicks on the VIDEO button, there is currently no video that shows up in general. I am concerned about this one because teachers are looking at the system right now, and no videos are showing up.

This is because the algorithm is incorrect.

There are two ways to retrieve a video when a student clicks on the example button:

A video is associated by hand to the current problem record (video field?) in the problem table.
If there is no video associated to it, then the algorithm should check other problems with the same standard as this problem, and see if they have videos associated to them.

It is very possible that other math problems (for the same standard) have a video assigned to them. This video should be sought for and shown for a problem that has the same standard as the current problem, and has the closest problem difficulty to the current problem.

It is possible always that there is NO video associated to any problem of this current standard. Then it should fail and say there is no video. But that should be rare.

It is possible that more than one video is found for other problems with the same standard. If so, the video for the problem of closest difficulty as the current problem should be shown.

--Ivon

**Comment by FrankSylvia** [comment]
I verified this issue is fixed by testing problem #1552 in the 'Ratios and Proportional Releationships - Review' topic.

There are many problems with no video available.
