### ISSUE TITLE
Can't go to the practice area from the "learn more" tab

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#194]
I get this error ack=false&message=For input string: "". I had to hit the back button then click "my progress" get back to that screen then click "practice area"

**Comment by IvonArroyo** [comment]
Yes, this is an issue.  --Ivon
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by perspegrity5** [comment]
Do we have a related issue in the system to catch the browser back button and stop it from executing?

**Comment by mkartik** [comment]
I have tested the issue on the dev environment.

**Comment by IvonArroyo** [comment]
Hi Tom,

At one of the meetings we agreed that it is impossible to catch the back
button from the browser.
I don't think this is the problem, as the back button in mathspring should
take you to a reasonable place.

ack=false&message=For input string: "

This is probably a navigation issue from the SPP,

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002
