### ISSUE TITLE
Manage Student - refreshing the page it goes back to Manage Topics.  Should go back to Manage Students.

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#196]
When I add the student's last and first name there is really no way to transition out of the dialogue box. Also I never see the changes.  One way I can get around seeing the changes is go back to the home page and then go back into the class (which directly brings me to problem sets) and then I have to click on manage students.

I clicked add student IDs and a note popped up saying creation successful, however, it was not optimized for my computer screen, not sure how to fix this. Also, a message told me to refresh so i did and something went wrong and I got an error page with lots of code on it, that only happened once

**Comment by IvonArroyo** [comment]
Creating a "Home" page for each class that shows its information, and indicates to choose an option from the menu bar to continue.

**Comment by mkartik** [comment]
I have tested this issue on the dev environment.
