### ISSUE TITLE
Resetting password - very confusing description of problems

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#197]
Something funky is going on here. When I created my teacher and student account I used the same email.  I tried the forget password button and when i use that email it gave me my student login even though I said I was a teacher. Then I tried it again...saying I forgot my password and putting in that same email and it said it was invalid.  Then after several more tries I toggled it to teacher put that same email address in and said they sent me an email but I never got an email...not even in my spam. Something is very strange. If we can't use the same email as a teacher and a student account then that should be noted. But I still think there is a bug here.

Ok so definitely wacky...  I created a new teacher account but I used the same username susanteacher as the one I created before.  I guess it recognized that and gave me a new username: susanteacher972.  I linked it to my yahoo account.  So then I went back in and pretended I forgot my password. I entered my user name susanteacher972 and it said the password would be mailed to me. I checked my yahoo and this is what they gave me... The password is supposed to be test. Is it supposed to change the password?.  Your login is: susanteacher972 Your password is: su87005$  Also I requested a new password using this login.  This was also created using my yahoo account. This is the correct login and psswrod. They didn't change the password on me.  Your login is: susanteacher Your password is: test But now when I go to login it says invalid credentials. So then I tried forget password with susanteacher and said it will be emailed to me. But it wasn't. I tried it several times and I am sill not getting an emai with a password for susanteacher.   i also have another username linked to my yahoo account starallo12. When I click forgot password I do get an email.  Your login is: starallo12 Your password is: st70610$

**Comment by IvonArroyo** [comment]
Frank, can you replicate the problem?

**Comment by mkartik** [comment]
As per the discussion, we would be removing the email id field from the Student Creation page. So, the first issue wherein the student and teacher can have the same email id would not occur. The second issue has been fixed.

**Comment by FrankSylvia** [comment]
The student and teacher emails are tracked in their separate tables.  I don't understand how there could be a collision.

**Comment by IvonArroyo** [comment]
We are not even tracking a student email. There is only a username for the
student, no email.
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Ok, I'll remove the email field from the Sign up Student form.

**Comment by WillRebel** [comment]
Resetting a teacher password sends an email with a new password in plain text. It appears to have a pattern to it, but I'm not sure if I should post that here.
