### ISSUE TITLE
Examples: The size of the window is too short and too narrow

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#202]
We need to update the size of the examples screen by about 10% taller and 10% wider, as the problems currently don't fit in the window.
Can we please do this ASAP? As a lot of problems are not great, get cut off, and it is the first thing a person sees when getting to the Practice Area.

**Comment by wlee-umass** [comment]
Will Lee testing

**Comment by FrankSylvia** [comment]
I had to change my video dsiplay resolution to 1600 x 900 to get everything to show up with only minimal scrolling.

What resolution are we expecting from our typcal users?

**Comment by wlee-umass** [comment]
If there are more than 5 steps in Show Example, a little got cut off but not a big deal

![image](https://user-images.githubusercontent.com/58573767/91189375-6290fd80-e6c0-11ea-931f-6d203bc8cce0.png)

**Comment by IvonArroyo** [comment]
It looks good! However, two details still, which will make me turn it back to 'Work in Progress':

1. The window should be positioned at the top, as there is a risk of the student not seeing the bottom button (Y value =0, at the very top). I couldn't see the button in my screen, and it is not obvious that you can move the window. Probably this will solve the issue

2. Please make the text be read aloud when you start the topic, such as when you come from the progress page. It doesn't happen all the time, only the first time you enter the topic that an example is shown.

**Comment by IvonArroyo** [comment]
Hi all, now the example window is too long.
Please make sure it doesn't go beyond the character's desk. My internet is really bad so I cannot retest this morning.

**Comment by IvonArroyo** [comment]
Can we please work on this issue again? AS we talked during the meeting, move to the top of the screen, and make the button be not further than the bottom of the characters desk.

**Comment by mkartik** [comment]
The position of the example dialog has been fixed till the bottom of the characters desk.

**Comment by IvonArroyo** [comment]
And has the window been moved to the top of the screen also? Otherwise the
example won't fit
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by IvonArroyo** [comment]
This is OK now in the QA version of MathSpring. I will close this issue.

**Comment by IvonArroyo** [comment]
I am reopening this issue, because one of our teachers says that the students cannot see the "next step button". Apparently, we really have to keep the height of anything visible by the bottom of the desk of the character.

I resized to the bottom of the desk and got this:

<img width="1531" alt="Screen Shot 2020-11-11 at 1 10 00 PM" src="https://user-images.githubusercontent.com/5631787/98848459-c1dcef00-241f-11eb-9c05-74ce9a0fc4a4.png">

When choosing "view page source" I got this below. I believe if we only shrink the "height" of each of these by 25 points, we should be fine. Let's not touch up on the width.

<div id="exampleContainer" width="650" height="650"
--
  | title="Watch/listen to this example. Use 'Play Next Step' to move along">
  |  
  | <iframe id="exampleFrame" name="iframe2" width="650" height="650"
  | src="" frameborder="no" scrolling="no"> </iframe>
  | </div>
  |  
  | <div id="utilDialog" title="">
  | <iframe id="utilDialogIframe" width="675" height="675"> </iframe>

**Comment by IvonArroyo** [comment]
We talked about moving the button of 'next step' to the top, because of resolution issues.
