### ISSUE TITLE
Layout is not properly rendered

### ISSUE THREAD

**Issue by tuotuoZ** [center-for-knowledge-communication/mathspring#209]
When an author changes the format of the problem under the layout tab, it doesn't reflect in the preview.

**Comment by IvonArroyo** [comment]
Can you say more Boming? Give an example?

**Comment by tuotuoZ** [comment]
Hi Ivon, It's fixed now. I just tested. I didn't do anything to fix this.

The problem was when content creators toggled between different layout settings, it wouldn't reflect on the preview page.
![Screen Shot 2020-09-25 at 10 11 48 PM](https://user-images.githubusercontent.com/40042621/94327902-3d700300-ff7c-11ea-8713-a4a4e904d144.png)
