### ISSUE TITLE
classDetails.jsp has grown larger then the 65K limit for JSPs

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#214]
We need to squeeze some space for now.

**Comment by FrankSylvia** [comment]
Some of the reports have doubled code size to accomodate multi-lingual.   See function problemDetails().

There is a way to use an include file for the language : parameter, but I could not get it to work and had to abandon it and use a shortcut to meet  the Spanish translation deadline in summer 2019.

There are several instance where we can gain back some space if we can get that to work.

**Comment by IvonArroyo** [comment]
Spanish translation is not a priority right now... But it will be in about
1 year again.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002
