### ISSUE TITLE
Flag to Pause student use of Mathspring

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#237]
(Ivon needs to set priority)
Add flag to teacher table PauseStudentUse.  
(Note: later we may decide it better to do this at Class level.)

At start this will be managed by hand (sql access).
Ivon: should we build the turn on/off of this feature into admin or teacher tools?
It might be good if we let teachers set this also.

Students can log in, and even set up their user name etc., but they will be blocked from using the tutor.
If a teacher has PauseStudentUse=1, then:
When students login who are in classes of that teacher, they get a screen that says
"Access to the MathSpring learning system is on pause right now. Ask your teacher for information about
when you will have access to MathSpring."
Actually: Have the above message be a string in the mathspring global variables table (see below). 
NOTE: only regular students are bocked/paused.  **Test-users** can still use the system as always. 

Frank - add an event to the eventlog that notes that a MS_pause_screen was reached for that student.

**Purpose**: 
During our large-scale implementation study (PALS) we want to make sure that students have taken a separate survey (and pretest) before they start using MS.  We will hear from WestEd when a class has taken the pre-test/survey and then by hand we will turn PauseStudentUse off.
- this feature could also be used in an emergency when we want to block student use for any other reason, e.g. there is a serious bug in the code.  Then we can change the Pause message (above) and set all teachers (or classes) to pause. Alternatively, we could create another global variable called "PauseStudentUseForAllTeachers" which would create the pause for everyone (except test users). Then we could pause and un-pause all users without having to set and unset it for all teachers/classes. 

**Testing instructions**. Test with:
- student login in for fist time and registering their name etc. 
- student already registered who logs in.
- test user

**Comment by FrankSylvia** [comment]
Test data:
teacher: fstester4/fs96253  is paused   (should show a Red banner message, students in this class should not be able to log in)
teacher: fstester5/fs98875# is NOT paused

**Comment by FrankSylvia** [comment]
Tom,

When you say "add an event to the eventlog that notes that a MS_pause_screen was reached for that student", did you mean the eventlog table.  That log seems to be very problem-centric.  Was there some other log you were thinking of?

**Comment by FrankSylvia** [comment]
When you mention globally disabling logins, might it be more useful to use research_cohort level disabling when that comes along as a part of the user heirarchy.

**Comment by perspegrity5** [comment]
On Sep 16, 2020, at 10:44 AM, FrankSylvia <notifications@github.com> wrote:

> Tom, When you say "add an event to the eventlog that notes that a MS_pause_screen was reached for that student", did you mean the eventlog table. That log seems to be very problem-centric. Was there some other log you were thinking of?

The problemHistory log is the more problem-centric one. Eventlog should include all types of events, including login, going to MPP, etc. The basic idea is that if the system is on Pause it would be good to know how many students "hit the wall" during that time.

**Comment by perspegrity5** [comment]
On Sep 16, 2020, at 10:49 AM, FrankSylvia <notifications@github.com> wrote:
> When you mention globally disabling logins, might it be more useful to use research_cohort level disabling when that comes along as a part of the user heirarchy.
> 
hmmm...not sure.  Class-based pausing is if students or teachers have not competed certain pre-system steps.  System-wide pausing would be if we found a serious bug and wanted to use a pause rather than a code roll-back.  I cant think of a cohort-based reason to pause yet---as right now for the PALs cohort the pause/go is by-teacher, when they and their students are ready to start.

**Comment by perspegrity5** [comment]
(This requests came out of our PALS team meeting today. )

Decided not to allow teachers to turn on/off the Pause feature. For now we will do that by hand in database as superusers (sql etc.).   But, don't pull out your code that lets the teachers do that, it may be useful in the future. Rather: create a global setting for "allow_teachers_to_unpause_student_use" which, if =1, will show those buttons that you have already created for the teacher tools. And set it to 0 for now.
