### ISSUE TITLE
Canvas of MathSpring Problems in HTML

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#247]
IA-- There is some issue with the length of some of the problems. Let’s discuss this at the meeting, take a look at this screenshot. We cannot really guarantee that they will have the screen resolution to see under the characters desk. At the same time, there is space wasted at the top. Is this MathSpring retrieving the problem text with that box? Is there some way to be more efficient with the space at the top, where the text of the problem is shown?

This is problem 1851:
<img width="1411" alt="Screen Shot 2020-09-10 at 10 45 02 AM" src="https://user-images.githubusercontent.com/5631787/92748704-67f27700-f353-11ea-90ae-19d950d18c7c.png">

**Comment by IvonArroyo** [comment]
Hi all, the issue is that a lot of the content developers have created previewing in rose.cs.umass.edu, and mathspring.org looks different. Take a look at these screenshots. I think reducing the font size by half a point would help, BUT will not solve all the problems, as the images are larger also. That is probably why many problems are falling off the screen.
<img width="1440" alt="2470_Rose" src="https://user-images.githubusercontent.com/5631787/92954808-1967da00-f432-11ea-8ff0-49874d7bf1ba.png">
<img width="1440" alt="2500_AWS" src="https://user-images.githubusercontent.com/5631787/92954819-1c62ca80-f432-11ea-9543-e3d9e870e84c.png">
<img width="1440" alt="2500_Rose" src="https://user-images.githubusercontent.com/5631787/92954828-1ec52480-f432-11ea-8ae4-f2172aa32df9.png">

<img width="1440" alt="2470_AWS" src="https://user-images.githubusercontent.com/5631787/92954800-15d45300-f432-11ea-8016-21e29184b4c6.png">

**Comment by IvonArroyo** [comment]
Actually, it seems that mathspring.org is making more efficient use of space! See how rose.cs.umass.edu reaches further down in the toolbar. Maybe just reducing the font size a little bit would help?

**Comment by tuotuoZ** [comment]
Hi all, what is the default resolution we are screenshotting at? I have a widescreen, and the layout changes under different setting. Here are two screenshots I took from rose. The first one with a slightly wider resolution, the other with normal resolution.
![Screen Shot 2020-09-15 at 10 54 43 AM](https://user-images.githubusercontent.com/40042621/93227332-3eb25c00-f742-11ea-9ef3-30258e580122.png)
![Screen Shot 2020-09-15 at 10 58 07 AM](https://user-images.githubusercontent.com/40042621/93227445-5d185780-f742-11ea-94f9-3442c8798eb0.png)

I believe there is a trigger point at the horizontal resolution, if it's smaller than that, then all the contents would be pushed to the top left.

**Comment by dallessio** [comment]
Hello, I believe, If you make a screenshot with your Mac, it'll always be in the resolution of the screen, my
13-inch MacBook Pro's native resolution is 2560 x 1600.

**Comment by tuotuoZ** [comment]
> Hello, my MacBook's default resolution is 1440 x 900 but it changes when attached to an external monitor.
> I took all the screen shots with a consistent resolution either all with my external monitor or all without my external monitor.

Hi Danielle, I am currently using a 21:9 ratio display, and the resolution is 2560 x 1080, which is hard for me to produce a comparable screenshot. Could you take a screenshot on problem 1851? I think your screen is a more general one, thus, leads to better comparsion here. Thanks!

**Comment by dallessio** [comment]
Boming, here is a screenshot of 1851. -Danielle
![Screen Shot 2020-09-16 at 9 31 46 AM](https://user-images.githubusercontent.com/6811862/93344685-f5c0dd00-f7ff-11ea-99ec-e6bf00dc95f2.png)

**Comment by dallessio** [comment]
Here is 1851 without my external monitor:
<img width="1440" alt="Screen Shot 2020-09-16 at 9 56 17 AM" src="https://user-images.githubusercontent.com/6811862/93347513-28b8a000-f803-11ea-91e1-bcd83956176a.png">

**Comment by tuotuoZ** [comment]
> Here is 1851 without my external monitor:
> <img alt="Screen Shot 2020-09-16 at 9 56 17 AM" width="1440" src="https://user-images.githubusercontent.com/6811862/93347513-28b8a000-f803-11ea-91e1-bcd83956176a.png">

Thanks!

**Comment by tuotuoZ** [comment]
@IvonArroyo  Hi Ivon, I think the target screen resolution is important in our future discussion. We might need to discuss this in the next meeting.

**Comment by IvonArroyo** [comment]
What is the problemID for this last problem with the shape to find the area for? CAn you include a screenshot from rose?

**Comment by dallessio** [comment]
@IvonArroyo 
The above probem is 1851 and here is a screenshot from Rose:
<img width="1440" alt="Screen Shot 2020-09-17 at 3 17 30 PM" src="https://user-images.githubusercontent.com/6811862/93517387-60097880-f8f9-11ea-8aaf-20f7c260039c.png">

**Comment by IvonArroyo** [comment]
So there is an issue with the images being larger on mathspring.org than on rose.
