### ISSUE TITLE
Restart the production MathSpring.org every night

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#248]
I am not clear if this is being done?
Restart the production MathSpring.org every night. It might be done already.

If not, can we get Jenkins to do this? 
This is because content developers want to be able to test the problems that they created the previous day, in mathspring.org.

**Comment by FrankSylvia** [comment]
mathspring.org has restarted every morning at 6:15AM local time since Aug. 29th.

de.mathspring.org has restarted every morning at 6:00AM local time since Aug. 28th.

**Comment by IvonArroyo** [comment]
Perfect, thanks!
