### ISSUE TITLE
Add the Name of the Class and Teacher at the top of the Practice Area, after the topic.

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#261]

**Comment by FrankSylvia** [comment]
Hi Ivon,
Ivon,
Ivon,

Please see attachment and confirm the format for teacher name  or suggests any changes.  

![Issue_261](https://user-images.githubusercontent.com/46008380/94952798-8829d780-04b4-11eb-9ef7-6c0b06edca9e.PNG)

Do you want this format to only show when you come in from the Practice Area or for all problems, e.g. from My Progress Page, etc?

**Comment by IvonArroyo** [comment]
Looks good!

It would be best in the Practice Area,  wherever you come in from.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by WillRebel** [comment]
It shows up in the Practice Area, but not in the example when you start a new topic. Is that intentional?
