### ISSUE TITLE
Details about new standards (mismatch in database and what shows up in Teacher Tools?)

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#266]
Hi Tom and Frank,

People att the conttent development meeting have been complaining about the number of problems per topic dropping instead of increasing. Tom is going to do some research about some topics that have disappeared (or been renamed? or never should have been there?)  that are in the CKC content agenda.

I am a little bit worried about this mismatch that I found in the database, for the new standards that have been created, for instance for equations and inequalities, take a look at this screenshot:

However, it seems that all problems are showing correctly (the ready ones show in the right topic for equations and inequalities). Is this something that we should fix, or not?

<img width="1138" alt="Screen Shot 2020-10-02 at 4 31 02 PM" src="https://user-images.githubusercontent.com/5631787/94967767-bcf65880-04cd-11eb-8b3b-5fdae72c6dc8.png">

**Comment by IvonArroyo** [comment]
Fortunately, it seems that the code is looking at standardID in the problem table, correct?, to display problems for teachers in the Teacher Tools, and also to choose problems for students in the current topic?

**Comment by perspegrity5** [comment]
I have attached a file showing the problems for all standards that are referenced by topics.  It does not show zero problems for any of the standards, but I think I need to study up on Outer Joins in sql to have another look.  (Yes, Ivon, standardID is the correct problem field.)

**Comment by IvonArroyo** [comment]
Shall we close this one?

**Comment by perspegrity5** [comment]
I think this has been solved. Lets close and reopen if teachers notice something new.
