### ISSUE TITLE
Bug about configuring class in Teacher Tools

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#267]
When I went to re-configure a class, I found that several of the pull down menus had NO value (grade, complexity), while obviously there was a value for those fields for that class as it had been created. Note this is probably the source of the bug.

I changed some parameters (but not others that were left blank, I forgot to set the grade level) and then hit submit and it was alright but gave me two grades only. Then I went back to change the grade, I realized the grade was blank with no value, changed it to 5th grade, and I got this exception attached.

<img width="1363" alt="Screen Shot 2020-10-02 at 4 42 15 PM" src="https://user-images.githubusercontent.com/5631787/94968358-be745080-04ce-11eb-9853-d918968ddaf9.png">

**Comment by FrankSylvia** [comment]
Was this in mathspring.org  or dev?

Can you tell me the teacher username & password and the class id so I can try duplicate this.

I was unable to break it with the class I created.

Also I have a new version of configure class in dev that I am testing because not setting the schoolYear gave me a similar error.

I'd like to get this fixed and tested today if possible.

**Comment by IvonArroyo** [comment]
Hi Frank,

It is very likely that simply making sure that all entries are populated
when you submit will solve the problem.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Ok, Thanks

**Comment by WillRebel** [comment]
I tried reconfiguring a class: dropdowns have the normal values. I was able to change everything in the class (name, section, school, etc). Is it intentional that after you reconfigure the class, you get sent back to the teacher home page?
