### ISSUE TITLE
Adding Labels to issues that have interface changes

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#268]
We should label all the issues that have had (or will have) interface changes.
I created a new label called "Interface Chance".

**Comment by FrankSylvia** [comment]
I have viewed the teacher tools videos and as Ivon has pointed out, the UI has changed quite a bit from a navigation perspective, particularly sections 2-6 to 2-15.  

Much of the functional descriptions are unchanged. 

We have 2 servers hosting the Mathspring application, Mathspring.org which will be the publicly available version and dev.mathspring.org (DEV\QA) which has the latest versions that we are testing right now.  I expect to sync-up the Mathspring.org with DEV\QA) on Thursday 10/15/20 if all goes well. Feel free to use the DEV\Qa server to get an idea of which videos need re-doing.
