### ISSUE TITLE
Allow students to choose one of the two characters (pedagogy) after log in

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#274]
There are two pedagogies that are allowed for this class (classconfig table). Once a student is created they are assigned one of the two and stays there forever.

The idea is that once a student logs in, they are given the choice of a pedagogy. The image of an idle character for each of the pedagogies, together with he pedagogy name should be available for a choice.

The student should be asked: Choose one of these:

The character that corresponds to the pedagogy plus the name of it should be available for choice

EMPATICJANELC                          EMPATHICJAKELC
<picture of Jane, idle>               <picture of Jake, idle>

When they click on the box, the pedagogy is updated in the student table (pedagogyid field).

--Ivon

**Comment by perspegrity5** [comment]
seems like a good area for Kartik to take on. What do you think Kartik?

Suggestions: 
- The implementation should be extensible to however many characters we create in the future.
- Some students may enjoy, and thus have less boredom and more engagement, if they select "I'd like to see all of them" and the character is selected randomly each time.
- Students may want to change the character from one session to another (i.e. their choice should not be final)

> Also, while we are thinking about it, just to note: Dave Marshal and I spec'ed out a system for character "skins" and firing rules. There was a lot of effort and code built and some of it got released but I'm not sure how much. Kartik may want to look at into it.  I can share the specifications etc.

**Comment by perspegrity5** [comment]
Ivon, I'm wondering why this one is super-high priority.  Do we have priority-creep? :-)

**Comment by mkartik** [comment]
Sounds good! Tom, can you share the specification document that you mentioned earlier with me, it would help me design the flow for this functionality. Also, thinking about the third suggestion, if we want that the student can change the character from session to session, we would require a _student profile menu_ that the student can access to change the character.

**Comment by perspegrity5** [comment]
Hi Kartik. [I sent this response in October and it should have appeared here but looks like it did not!]

Sorry for the delay.

You may be able to do the easy parts of this task without knowing about all of this stuff, but I think it would be great if you gained some expertise in this part of the code for future work. 

First is a sheet where we are developing the Character message content:
https://docs.google.com/spreadsheets/d/1hE7ktiKeRT7BjBlyX-i7v-4jk3IaO_-l5vxq2w0XrfA/edit#gid=2 

The actual sound files are prototyped in this folder, but the final versions are on the AWS file server on mscontent/LearningCompanion.
https://drive.google.com/drive/folders/0B_dUxqCpzSjOZWNHaEhWdFFvYXc

We spec'ed out a rule language for deciding when the LC messages would fire. Some of this was implemented by Dave Marshall but I don't know how much made it into production.
Learning Companion Rule language spec:
https://docs.google.com/document/d/1xCmJSk7B6Mmr6tUv61gCqRwlhwLSSks64HCwTRSgHTY/
with the orgincal ideas based on this:
Orig Design #1 Data-driven Learning Companion -- proposal v.1
https://drive.google.com/drive/folders/0B8aG9e7moczwOFJ6VUhzbzYtdnc

probably too much info! -- but there you have it!
Happy to talk about any of this--it will take a minute to re-start my brain on some if it as its a few years past

--cheers,
Tom

**Comment by IvonArroyo** [comment]
Message:

I want to work with ...

**Comment by IvonArroyo** [comment]
Kartik, I meant to say that we need to log (in the eventlog table) the choice of the student, a new row where action could be chooseCharacter, or choosePedagogy, and the number of the pedagogy can go in userInput

**Comment by IvonArroyo** [comment]
Update on this, please?

**Comment by IvonArroyo** [comment]
This one is ready to close
