### ISSUE TITLE
Teacher Administrative (Master Teacher) login

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#276]
We want to be able to choose a Teacher (similar to the Teacher Activity) and be able to "pretend to be" a teacher, so that we can actually see what they have done in the teacher tools and the reports of their students.

The idea is to be able to see without getting any data logged for that teacher.

**Comment by IvonArroyo** [comment]
What is the status of this?

**Comment by FrankSylvia** [comment]
"At present there are no restrictions, and logging will be logged under the teacher's account."

So do you mean that you are actually logging the activity if we log in "as the teacher"? Is there a way that you could NOT log what we do in the teacher log?

**Yes** 
I can omit the logging of what we do in the teacher log, or I could mark any logged item as having been done by the Master Teacher, if you want some accountability.  Please let me know if you want this.

Meanwhile,  I'll start working on preserving the fact that you are logged in as the Master Teacher.
