### ISSUE TITLE
A zoom (magnifying) capability for the Images

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#277]
People have suggested that we add some sort of functionality to zoom in to see images better.

Magnifier tool, or simply the ability to open the image in a new pop-up window.

**Comment by perspegrity5** [comment]
Its seems standard these days on the internet to just mouse-over an image and expect a pop-up magnification; with a disappear when you mouse off of it. I think that would be the simplest.  Note: do this for main and hint images. Also, *if* it is not a lot of extra work, the functionality should work for videos as well as images.

**Comment by FrankSylvia** [comment]
for main image and hint images
