### ISSUE TITLE
Password recovery/reset for both students and teachers

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#28]
Really important for the IES study!

**Comment by FrankSylvia** [comment]
This doesn't apply for students now that we are using the class id as the password.

We could ask them to enter the class code for one of their classes. If they get it right, we could let them choose a new password.  

Please comment so I can proceed...

**Comment by IvonArroyo** [comment]
Does the classID also work for teachers? It seems that the password recovery is especially important for teachers.

**Comment by FrankSylvia** [comment]
It does not,  but we could make it so that is they enter may any one of
their class Ids.  Should I go ahead with that?

**Comment by FrankSylvia** [comment]
Hi Ivon,

I have finished with this issue.

Do you think we should put a reminder somewhere that teacher's should jot
down their class Ids? (maybe in 'Create Class')

Frank

**Comment by IvonArroyo** [comment]
I think we should have a link that says 'Forgot Password?' and says that if
you are a student, you should ask your teacher for your password, and if
you are a teacher, it would email them their classIDs .

------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
ok

**Comment by FrankSylvia** [comment]
When teacher selects 'Forgot password', he/she is assigned a random 6 digit numberas a new password.  An email is sent to the teache (NOT CURRENTLY WORKING). 

The teacher is then sent to the Login page to login with the new password.

The teacher may continue to use that password or go to teacher edit profile and change it.

**Comment by IvonArroyo** [comment]
This currently doesn't work for the teacher.
There are two scenarios: 1) No username is entered and the teacher marks 'Forgot Password'. If no username is entered, then an exception is happening. 

2) When a username is entered and the teacher marks 'Forgot password', it hangs, just waits for ever. Check the file Mailer.java.  
There is an example at the bottom on how to create an instance of the mailer, with TO, FROM, SUBJECT, TEXT, and MAIL SERVER. 

Mail server should be: mailsrv.cs.umass.edu 
FROM should be: mathspring@cs.umass.edu

See if it works!  --Ivon

 public static void main(String[] args) {
        System.out.println("Trying to run a test of Mailer");
        Mailer m = new Mailer("marshall@cs.umass.edu","marshall@cs.umass.edu","subj","hi there", "loki.cs.umass.edu");
        m.send();
    }

**Comment by FrankSylvia** [comment]
I was unable to connect to the mail server.
Here's a snapshot of the code and error mesage
![image](https://user-images.githubusercontent.com/46008380/81473280-4e85c680-91cb-11ea-8737-d8aff15e4897.png)

Here is a snapshot of the mailsrv.cs.umass.edu.  Should I be able to log in as mathspring?
 I couldn't.

![umass_email](https://user-images.githubusercontent.com/46008380/81473347-cc49d200-91cb-11ea-8caa-1b1bf1b52755.PNG)

Any ideas on why?

**Comment by IvonArroyo** [comment]
I don't see evidence that you entered the correct password to the
mathspring@cs account?

Can you get this email? Does variable v have a random number for password?
Also where is it sending the password in the call?

---Ivon
------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by IvonArroyo** [comment]
This issue is not completely solved yet. We can move it as it is to the deployment version, but I wouldn't say we can close the issue.  

There is something about the way you interact with the forgot password feature that is very strange.

Talking with Erik today (who is creating the PD) we agreed that most web sites have the "Forgot Password" as a link and not as a check box. If you click on the link, you should be taken to another page that asks you for your email address (or your username), and whether you are a teacher or a student.

**Comment by FrankSylvia** [comment]
Hi Ivon,

I would like an opportunity to have a conversation about this.  Is that
possible?

Thanks,
Frank

**Comment by FrankSylvia** [comment]
I implemented it, and then when we discussed it, it was the consensus that
the students would figure it out and then it wouldn't be very secure. So I
removed that functionality.

if you want me to put it back I can do easily do that.

Let me know.

Frank

**Comment by IvonArroyo** [comment]
AS we discussed yesterday, the 'Forgot Password' should be a link that takes you to a new page, where it asks. 1) if you are a student or a teacher,  2) the email address and user name.

The email sent to the teacher should be a bit more explanatory, saying :

"You asked for your MathSpring credentials:

 username = ...
password=...

Once you log in, you can change your password again if you want from the "Edit Profile" option in the Teacher Tools.

**Comment by FrankSylvia** [comment]
Thanks, that really helps.

**Comment by IvonArroyo** [comment]
Edit Profile (to change password) should change from the profile option icon att the top left corner of Teacher Tools

**Comment by FrankSylvia** [comment]
I'm confused.

I got 5 action items from Erik.  Am I supposed to act on those or wait for your approval?

if I understood it correctly, one of the changes was to move Edit teacher Profile from the left panel of the teacher's Home Page to the dropdown in the upper right corner.  Here is his image.
![editprofilechange](https://user-images.githubusercontent.com/46008380/83047020-cbab9b00-a015-11ea-9722-a4e306abf926.PNG)

**Comment by IvonArroyo** [comment]
Hi Frank,

We need to create tickets for these at least. If you can create a ticket
for each item, that is huge progress and more important than just acting on
them.

Then we can prioritize, so far it is most important to only work in the
items that have high priority on them.

------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by FrankSylvia** [comment]
Does this look OK?

It will link to some sort of 'Help Request' form.  (See issue #135)
