### ISSUE TITLE
Cannot activate 'archived' classes, they get stuck down there

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#283]
Jenny Finnie is a teacher who talked with Danielle and Sai today, because her class somehow got archived and cannot get it unarchived.

I think we discussed about the issue of previous years' classes getting archived automatically? Giving it a second thought, NO classes should be automatically archived unless the person decides to archive them.

More importantly, the RESTORE function is not working.

Could we fix this ASAP? As teachers who created classes during he summer have not been able to retrieve the classes that somehow got archived.

If I look at Jenny Finnie's class (teacher ID = 946) and her only class created (class ID = 1709)  I can see her class is active in the database (active=1), so no idea why it is getting archived.

However, if I log in with teacher ivon/ivon, if I try to RESTORE my archived classes, I get a flash second message saying that student access is locked, and then the class stays archived. I wonder if student locks could have something to do with this?

**Comment by FrankSylvia** [comment]
I released the fix this morning.  It had to do with the SchoolYear which I was using to control Active vs Archived.  I have taken that test out of the code.

**Comment by IvonArroyo** [comment]
Hi Frank, Yes! I saw. It seems to be working now.
Thank you.
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst
Amherst, MA 01002

**Comment by WillRebel** [comment]
Restoring my archived classes also works on dev
