### ISSUE TITLE
Mastery Update is Incorrect, goes down to 0.1

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#286]
I have seen several instances of this (see screenshot) over the years. I believe there is a bug in our logging that adds a 0.1 by default or alike. Then somehow the code doesn't update the mastery value correctly in the studentproblemhistory table, and the result is that the default 0.1 value is shown. The interesting thing is that it does not LOSE the previous mastery value, because it recovers as you can see.

This is just someone in our 6th grade sample class (teacher ivon/ivon) testing some problems (class code= 1657 , user: NastiyaTest, topic='Coordinate Geometry', #29)

<img width="821" alt="Screen Shot 2020-10-20 at 2 34 49 PM" src="https://user-images.githubusercontent.com/5631787/96629758-10e0aa00-12e2-11eb-8cd2-b1c8758ad56e.png">

**Comment by dallessio** [comment]
Yes! I have been bringing up that I feel that there is a bug in the Mastery code for the past few years. Various students and teachers have asked me if the Mastery bar is broken.

**Comment by IvonArroyo** [comment]
It is hard to replicate these issues. I believe the solution is to enter the last mastery in studentproblemhistroy as SOON as the problem is loaded. Then, if we never get to update it for some reason, at least the value it has is the same as the last time.
