### ISSUE TITLE
Exception upon teacher login

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#29]
This keeps happening, the exception after a teacher logs in. It could be that the teacher did not log out, unclear.
See attachment.
<img width="844" alt="Screen Shot 2019-11-14 at 2 35 30 PM" src="https://user-images.githubusercontent.com/5631787/68890235-74cf1b80-06ec-11ea-823f-1e156a9859ff.png">

--Ivon

**Comment by FrankSylvia** [comment]
Ankit, This doesn't seem to be happening any more in 'Dev'.  Did you change something to fix it?
