### ISSUE TITLE
Auto-creating test users for new classes

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#292]
Create test users automatically for new classes so teachers don't have to. 

Create 4 test users whenever a class is created.
The names are xxxtester1, xxxtester2, xxxteststudent1, xxxteststudent2.
Where xxx is the class ID.
The passwords are all 'mathspring'

The relevant student table fields are:
trailUser
keepUser
keepData
updateStats
showTestControls

For tester1, tester2:
trailUser = 1
keepUser = 1
keepData = 0
updateStats = 0
showTestControls = 1

For  teststudent1, teststudent2:
trailUser = 1
keepUser = 1
keepData = 1
updateStats = 0
showTestControls = 1

**Comment by mkartik** [comment]
@perspegrity5 , there could be a conflict across classes, if the same username is used for the test users. So, we might have to think of a different way to create the usernames for the test users.
