### ISSUE TITLE
Home Landing page for Teachers

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#299]
Teachers have suggested that the landing page should have information about the students who have logged in during the last week (7 days) and how many minutes they have been in MathSpring. Also, how many problems have they seen.

**Comment by IvonArroyo** [comment]
I suggest the following:

These are students in these class that have worked on MathSpring this last week:

Student name           Last Login Date                 Minutes in MathSpring (last 7 days)               Number problems seen (last 7 days)

**Comment by IvonArroyo** [comment]
I tested the landing page for a class. It works well! I saw 1 example, 1 problem (which I solved), and then hit next problem and logged out. It is 4:38pm now.

The screen that I got is attached.


<img width="1311" alt="Screen Shot 2020-12-09 at 4 39 01 PM" src="https://user-images.githubusercontent.com/5631787/101691713-18e4dc80-3a3d-11eb-9500-e2e3428e274d.png">

Main issue is that the time says that I logged in at the correct date, but the time is wrong.
One possibility is to eliminate the time, I don't think that we care about the time.

SEcond thing is that it says "Number of problems attempted" = 3, while those are the problems that I encountered, not the ones that I attempted. Changing it to "Number of problems encountered" or "Number of problems seen" would be better.

**Comment by IvonArroyo** [comment]
WE could also say, at the bottom, See more details in the Class Report Card.

**Comment by IvonArroyo** [comment]
Frank, I lost the submit button. There is no way to re-submit for a different date.
After I try to close the report, the brown line doesn't go away, and the submit button disappeared.
See attached screenshot.

<img width="1229" alt="Screen Shot 2020-11-19 at 1 53 59 PM" src="https://user-images.githubusercontent.com/5631787/101692150-c22bd280-3a3d-11eb-96b7-49243dae24cb.png">

Still, even with these bugs it is really worth adding to the production version! Super useful.

**Comment by FrankSylvia** [comment]
Changed presentation to be more clear about re-freshing with new number of days
Also fixed bug where > 1 minute showed 0 minutes. Now rounds up.
