### ISSUE TITLE
Classes don't load topics, when the name of the class has a '  in it. (Mr. Liner's Math Class  2020-2021)

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#302]
During the meeting with Paul Liner this morning, we couldn't load any of the two topics we enabled, when we logged in as a student:

Multiplying/Dividing whole numbers
Add/Subtract Fractions

We get white screens when entering the topics.

Student User : testliner password 1721 (that is the class) .

**Comment by IvonArroyo** [comment]
<img width="662" alt="Screen Shot 2020-11-06 at 12 05 42 PM" src="https://user-images.githubusercontent.com/5631787/98394251-7a71ef80-2028-11eb-8e51-5ce2d7002081.png">
<img width="1105" alt="Screen Shot 2020-11-06 at 12 05 25 PM" src="https://user-images.githubusercontent.com/5631787/98394252-7b0a8600-2028-11eb-99d3-9440d2734322.png">
<img width="844" alt="Screen Shot 2020-11-06 at 12 05 02 PM" src="https://user-images.githubusercontent.com/5631787/98394253-7b0a8600-2028-11eb-9257-d0eccbf40e2a.png">

**Comment by FrankSylvia** [comment]
I think we need a more comprehensive approach to this error.  This is a classic 'garbage in / garbage out' issue.

There is currently little or no validation of some of the user entered information.   To address this, we could:
- validate for certain characters like ' and " on the user entry forms and not accept them as valid entries
- escape ' and " before writing them to the db
- allow only a certain set of character, e.g only alpha, digits, certain special characters like @ _ . -
- some other approach?

Please comment.
