### ISSUE TITLE
Logging in as Lisa/O'Connor gives an exception, cannot log in at all

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#307]
Hi all,

The error of teachers logging in got worse: I cannot log in any more with Lisa O'Connors address.
Take a look: http://ckc.mathspring.org/ms/tt/tt/ttMain

**Comment by FrankSylvia** [comment]
This was caused by null-values and too-large data values in the classconfig table.  (MaxTimeInTopic column)

I added tests for each of the 4 newly-in-use fields to keep them within the min/max boundaries specified in Issue #293.

Changes will show up tonight in Mathspring.org

**Comment by IvonArroyo** [comment]
I have been able to log in with Lisa's username perfectly well.
