### ISSUE TITLE
Message at end of Review in Spanish!

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#315]
Teachers have complained about some of the messages in the screen coming up in Spanish:

I reproduced the error with a topic that has few problems, after you answer all problems, you can go and choose 'Review' from the progress page. When you end the review, the following message shows up:

"Usted ha completado la revisión. Utilice la página Mi progreso para seleccionar su próxima actividad.."

Also there is a message that shows up in spanish, that apparently is at the end of the regular topic, without reviewing:

"Ha terminado con este conjunto de problemas en Mathspring. Cierre la sesion o use el boton de Mi progreso para seleccionar problemas de revisión"

Can we please solve this ASAP? The teachers have complained and students are starting to lose credibility because of this.

**Comment by perspegrity5** [comment]
or we could say that we are teaching math and Spanish both! wow!
:-)

**Comment by IvonArroyo** [comment]
Thank you very much. for finding this bug!
Danielle says: 

Please also keep in mind, that I am still also trying to figure out why both Paul and Alyson reported yesterday that their students were getting the Spanish learning companion.  I will ask them to check their browser language.

--Frank is there any possibility that they would get the character in Spanish if their browser is set to English? Never happened to me!

**Comment by IvonArroyo** [comment]
An update to these two messages, to tell them that they can also click on 'Next Problem' to move to the next topic:

"Utilice la página de Mi Progreso para seleccionar su próxima actividad O apriete el botón de Próximo Problema para continuar con el próximo tema"

"Choose the My Progress Page to choose your next activity OR click on the next problem button to move on to the next topic."

**Comment by FrankSylvia** [comment]
I found 2 other instances of the same error. The files in error were:
revewDone.html, challengeDone.html and noMoreProbe.html

The error is that I was testing for "en" instead of "en-US" in the browser info variable.

So I wouldn't have to disrupt users, I have patched the Mathspring.org server with the fix because I could simply edit the html files.  The patch only contains the error fix.  The requested text changes will come along tonight when the files in github are pushed to Mathspring.org.

**Comment by IvonArroyo** [comment]
Perfect!  --Ivon
------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her
