### ISSUE TITLE
Error reported when reviewing topic 54

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#332]
Student was reviewing topic 54.

Student reported 🔢 

"Something went wrong and Mathspring keeps on saying there is an error going on and I don't know how to fix it. When I try it keeps on saying error, and I left off on a bus problem about ratios. The we clicked review and it took me to a problem about comparing."

We should test reviewing this topic and see what happens.

**Comment by IvonArroyo** [comment]
I would try to reproduce this bug by adding topic 54 to the list, going throuhg the whole topic, and then attempting to review the same topic 54.

**Comment by FrankSylvia** [comment]
There is no longer a topic 54.  Can I close this?

**Comment by FrankSylvia** [comment]
Topic 54 no longer exists.  Closing this issue.
