### ISSUE TITLE
Video selected for an english problem, should always be in english

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#333]
Student reported that the video shown was in Spanish, when it should have been in English.

For problem 2557, the problem is in english, but the video selected is in Spanish.

Right now, there is no video assigned to that problem, so it is looking for another video for the same standard.
It finds another video, but it is for a SPANISH problem, and the video is in spanish. So it shows a spanish video, when the video to be shown should be NONE, as there is no english video for any problem of that standard.

Take a look at this:
select id, name, statementHTML, language,video, standardID
from problem
where standardid='5.NBT.1'

--Ivon

**Comment by perspegrity5** [comment]
As a start to addressing this, I just added a field "language" to the video table. 
I set the default and all of the values to "English"
Then I found there were four Spanish problems that had videos. I set the video-language those four videos to "spanish"

So it is ready to coders to check the video language before giving a video.

NOTE: Authoring tools where new videos are created will need to specify language as well.
