### ISSUE TITLE
When switching classes for a teacher, error comes up.

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#358]
It happens only sometimes, for teachers that have MORE than 1 class, and you try to go from one to the next. 
Also, when logging in after logging out, and you go choose a class again. 
Maybe it was hard to test because you have a single class. Try user Lisa O'Connor that has several classes.

<img width="515" alt="Screen Shot 2021-01-13 at 4 11 13 PM" src="https://user-images.githubusercontent.com/5631787/104512381-19344280-55bc-11eb-8284-ee2b3a798892.png">

**Comment by FrankSylvia** [comment]
This change prevents teachers from logging in to mathspring a second time when they are alreadsy logged in.  It also prevents users from logging in to 2 different teacher ids concurrently.

The following error message is displayed:
Multiple concurrent teacher logins have been detected. Only one teacher can be logged in at time. Note: Your open sessions have been terminated. Please close your session windows and log back in one teacher at a time.

**Comment by IvonArroyo** [comment]
This seems to be working fine now. Shall we close it?

**Comment by FrankSylvia** [comment]
I'll close it.

**Comment by FrankSylvia** [comment]
Re-worked the solution to not required the teacher to log login in a second time.
Super user login is prevented if the actual user is already logged in.

Normal user login test entered login id against session login id, if different kill the session and have then try again. This may occur if the actual teacher tries to open 2 sessions simultaneously on the same computer (not allowed), or if the URL has been edited to switch teacher Id. (This would be a hack.

Researcher login just kills the previous session and creates a new one.
