### ISSUE TITLE
Problem 1418 hangs in javascript

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#364]
javascript error event handler event type = element

hangs with no right answer

**Comment by FrankSylvia** [comment]
After sampling several problems where the problem column form="normal", I have come to the conclusion that none of them are working correctly.  The answer field is unresponsive.

Somce of these problems, e.g 1418, are status=ready, but many are onle testable. Should any of these problems be available?

**Comment by dallessio** [comment]
Hello, the testable problems should not be showing up in the live system.
Only problems that are set to Ready should be available.
Best, -danielle

**Comment by FrankSylvia** [comment]
Problem was not supposed to be in ready state.  Fixed by Tom.
