### ISSUE TITLE
Teacher feedback buttons

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#383]
Purpose:  1. Allow teachers to easily send feedback on problems.  2. Allow them to easily provide feedback on the teacher tools.

Design suggestion: 
1. In the problem previewer tool, add a button "Send feedback for this problem".  It brings up a dialogue "Enter your feedback from problem [##] [name]". with "Choose priority" serious issue, minor suggestion, other. 
2. new database table: teacher_feedback.  Columns:  ID, teacher ID, timestamp, messageType, priority, objectID.  MessageType is "problemPreviewFeedback" or "teacherToolFeedback" (and we may add more later).  Priority is "serious issue," "minor suggestion," "other". ObjectID is, in the case of "problemPreivewerFeedback", the problem ID. 

- Extra feature: include "upload a screenshot picture file (you have to take the screen shot yourself first)"

3.  Add a button to the entire teach tool suite, at the bottom of the left hand menu, for "Teacher Tools Feedback" that brings up a dialogue saying "Please note any bugs, suggestions, or comments about the Mathspring Teacher Tools below. (Note: to give feedback on a specific problem, go to the xxxxx menu and use the problem previewer."

**Comment by FrankSylvia** [comment]
I have completed Parts 2 and 3.  Please test the teachertools implementation and give me feedback while I work on Part 1 which has a more difficult UI but uses the same back end.

**Comment by WillRebel** [comment]
It is easy to send comments from the Teacher Home tab (3)

There is nowhere to send comments once you are in a class, would it be possible to keep the feedback form as an option while in a class as well?

I don't believe I have access to check the second table, although I did send a test feedback,
