### ISSUE TITLE
Password for a batch of students created from Techer Tools

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#39]
I would like the password for a class, when the set of usernames are created, to be the CLASSID instead of waiting for the teacher to type in a password. We should tell the teacher that the password is a class code and give them the number.

In the mathspring.org interface front page, we should say "password or class code".

Class Code should be present in several places in the Teacher Tools, such as in the title of the class for instance.

WE could still reset the password if needed.

A student should be able to log in if their password is their classID.

**Comment by IvonArroyo** [comment]
The LABELS generated for the students in the class should provide the class code as a password.

**Comment by IvonArroyo** [comment]
Add labels to the text boxes in the "Manage Students" option for "create usernames"/

**Comment by IvonArroyo** [comment]
Refresh the page after hitting the close button.

**Comment by FrankSylvia** [comment]
Testable for ecerything but page refresh

**Comment by IvonArroyo** [comment]
Fill the prefix field with the default value 'math'

**Comment by IvonArroyo** [comment]
This works!

**Comment by FrankSylvia** [comment]
Please test the forgot password feature.  It now sends email to the user with a generated password.  If things look godd, please set this issue to 'Ready to close".  Thanks.
