### ISSUE TITLE
Set a date range for all reports, in addition to last x days (or instead of)

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#391]
Set a date range for all reports, in addition to last x days (or instead of)

**Comment by WillRebel** [comment]
Copying from #418 
Hyperlinks seem to work in all the report cards (except the Detailed Activity and emotions which has no selection)
Date range for gradebook per problem, Class Performance per Common Core Standards, Gradebook per topic works
Gradebook per problem requires selecting a single student (no selection leads to a spinning wheel). This is the only report that allows for a single student to be selected
I think the new legends/color scheme work well
