### ISSUE TITLE
Ability to move students across classes

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#398]
Lisa and other teachers want more capabilities in terms of being able to manage students.

In particular: the ability to move students across classes

**Comment by WillRebel** [comment]
Moving students between classes seems to work how I would expect. Moving is easy (once I figured out where to go). It keeps the mastery level of the students involved. If a student has solved problems that don't exist in the new class, those problems populate in the Class Summary per common core cluster tab. It appears to correctly adjust the percent of class that solved on first, used hints, etc.
