### ISSUE TITLE
Check if the last hints of order #20 would be considered correctly as last hint

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#405]
We agreed that we would check that the hints that Tom created (last hint) that were missing are correctly added to the list of hints.

We have to Check if the last hints of order #20 would be considered correctly as last hint, and if the STep number in the labels is OK.

--Ivon

**Comment by FrankSylvia** [comment]
The hints are extracted from the Hint DB table sorted by the order column into array presrveing that order.
The order column is not included in the array and does not travel into the UI.
Step numbers are generated in buildProblem.js using the index of the hint in the array.

So the hints should be functioning as intended.
