### ISSUE TITLE
Teacher Tools - Show only problems completed in the last x days Report question and request

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#414]
**Number of problems seen -** 
Is this skipped through or solved? 
Can this be # of problems solved?

**How is Time solving problems (minutes) calculated?**
Does the time keep running if students walk away? (See 55problems/462mins) 

![Screen Shot 2021-03-08 at 3 53 24 PM](https://user-images.githubusercontent.com/6811862/110512989-bc449c80-80d3-11eb-9ecd-5b2e65bb42a3.png)

**Comment by FrankSylvia** [comment]
How about adding an additional column  for problems solved instead of removing 'problems seen'?

**Comment by IvonArroyo** [comment]
I think removing problems seen and changing it for problems solved seems like a great idea. These would be problems with solved=1, meaning they eventually entered the correct answer.
