### ISSUE TITLE
Teacher Tools -  Class Summary Per Student Per Topic report request

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#416]
Please freeze the 'Student Name' and 'username' columns on the Class Summary Per Student Per Topic report the same way as in the Class Summary Per Student Per Problem report. Ty

<img width="1073" alt="Screen Shot 2021-03-08 at 1 20 26 PM" src="https://user-images.githubusercontent.com/6811862/110514570-6ffa5c00-80d5-11eb-9567-11aa890b71d2.png">

![Screen Shot 2021-03-09 at 12 51 48 PM](https://user-images.githubusercontent.com/6811862/110515538-7dfcac80-80d6-11eb-8bf8-14fc97f4c7d8.png)

**Comment by WillRebel** [comment]
These are frozen, but they don't line up correctly causing weird highlighting:
![image](https://user-images.githubusercontent.com/71284897/116426494-c304ab80-a808-11eb-87d0-c2a8a5d6d605.png)
![image](https://user-images.githubusercontent.com/71284897/116426525-c8fa8c80-a808-11eb-93f0-439348a44dfb.png)

**Comment by FrankSylvia** [comment]
Mis-aligned rows will be addressed in a later release.
