### ISSUE TITLE
Teacher Tools - Class Summary Per Student Per Problem request

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#418]
Please add the ability to filter by a student so that teachers can work with a student one-on-one and show them their work without them seeing the other students' information.  Thank you.

![Screen Shot 2021-03-10 at 8 40 55 AM](https://user-images.githubusercontent.com/6811862/110638397-84456400-817c-11eb-8947-b04479ecbb32.png)

**Comment by IvonArroyo** [comment]
A second request regarding this report is to have each of the colored cells have a hyperlink to the problem's thumbnail. This way it won't be so cryptic.

The button at the top can be changed to be the plain name of the problem, without a button.

**Comment by FrankSylvia** [comment]
I have released my latest changes for this issue to the Dev server.  These include, ability to select single student, problem snapshot when hover over problem status cell, paging - 16 rows per page this was required to get snapshots to fit in the report area.

I also changed the problem status legend, to be displayed on demand, and not by default.  The screen was really over-crowded.

A request was made to change the column header from problem name (too crytic) to problem nickname.  Looking at the nicknames in the db, it is clear we need some way to standardize the size and content. I have not implemented this pending some feedback on how to proceed.

**Comment by IvonArroyo** [comment]
Contact Will Rebelsky to test this? #218

**Comment by WillRebel** [comment]
Hyperlinks seem to work in all the report cards (except the Detailed Activity and emotions which has no selection)
Date range for gradebook per problem, Class Performance per Common Core Standards, Gradebook per topic works
Gradebook per problem requires selecting a single student (no selection leads to a spinning wheel). This is the only report that allows for a single student to be selected
I think the new legends/color scheme work well

**Comment by FrankSylvia** [comment]
Hi Will. Can you please provide some additional information, teachers you
are using, and classId you are reporting so I can reproduced the spinning
hang.  And generally if you find a serious error in teacher tools,
teacherId and class would help a lot.

**Comment by WillRebel** [comment]
I'm using my test teacher account
Teacher ID 983, Class ID 1744
![image](https://user-images.githubusercontent.com/71284897/116587646-45ac6a00-a8e0-11eb-9064-37451e5fcef9.png)

**Comment by FrankSylvia** [comment]
Thanks. I'll check it out.
