### ISSUE TITLE
Possible Delay after emotion question

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#429]
Xinue's analysis of student complaints indicates that some students experienced uncomfortably long delays after submitting the Emotion question dialogue.  Please see if there is a reason for this that can have performance improved.

**Comment by IvonArroyo** [comment]
Maybe we should test?

**Comment by FrankSylvia** [comment]
The ony delay I observed was when an emotion intervention happened to coincide with a topic switch. In this case, the delay was about 2-3 seconds which is normal when switching topics.
