### ISSUE TITLE
REmove Next Problem Button?

### ISSUE THREAD

**Issue by perspegrity5** [center-for-knowledge-communication/mathspring#431]
From Content team and Danielle:  Please consider the pros and cons of removing the Next Problem button, and just moving to the next problem automatically.

TM suggestion: one possibility is:  after selecting the correct answer, if the student does not press Next Problem for 10 seconds, bring up dialogue: "Do you want to move on to the next problem now?" "Yes" or "No"
If they say No:  bring up text: "Press Next Problem button when you are ready.  You can also look at the Example, Hints, or Video for this problems, OR you can navigate to My Progress screen to choose what topic to study. "

**Comment by IvonArroyo** [comment]
We agreed about the next problem button being flashed after the correct answer is entered.
