### ISSUE TITLE
Topic Intro Screens cut off

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#435]
These topic intro images are displaying too big and are cut off.  Others tested are good.

![Screen Shot 2021-04-07 at 4 08 05 PM](https://user-images.githubusercontent.com/6811862/113927727-d7cac200-97bb-11eb-833e-69169b82ed71.png)
![Screen Shot 2021-04-07 at 3 52 15 PM](https://user-images.githubusercontent.com/6811862/113927732-d8fbef00-97bb-11eb-8f0c-e35fda0b24ef.png)
![Screen Shot 2021-04-07 at 3 51 29 PM](https://user-images.githubusercontent.com/6811862/113927736-dac5b280-97bb-11eb-8844-c8d3fb8eb47d.png)

**Comment by IvonArroyo** [comment]
These are in the S3 bucket, under mscontent/intros. or alike

Could you check what is going on with these topics?
I think it is the html that is not resizing the image, what is different from other html from other introductions?

**Comment by mkartik** [comment]
@IvonArroyo, I looked at these topics and the corresponding html file in the S3 bucket. While analyzing the html files for these topics, I noticed that there is a "space" during the CSS style set in the HTML tag and that is causing the issue. We might have to individually go to each html file and make the update of removing the "space" before the inline CSS style tag.

**Comment by FrankSylvia** [comment]
Please review/and correct the topic intros which are in this condition
