### ISSUE TITLE
Changing the NAMES of the reports in Teacher Tools

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#442]
The names in the teacher tools Report Card are very cumbersome, and not aligned with what teachers are used to seeing in Google Classroom, for instance.

I think we should change the names of the reports in the following way:

Class Summary Per Student --> Gradebook with Detailed Activity & Emotions
(also change the first tab, FROM: **problems solved today** TO: **problems solved this week**, for the last seven days)

Class Summary Per Common Core Cluster --> Class Gradebook Per Standard

Class Summary Per Student Per Topic --> Gradebook Per Topic

Class Summary Per Student Per Problem --> GradeBook per Problem

**Comment by IvonArroyo** [comment]
Please move this one to the TOP of the list:
Class Summary Per Student Per Problem --> GradeBook per Problem

**Comment by FrankSylvia** [comment]
I have done the textual changes.  Next I will change the FROM: problems solved today TO: problems solved this week, for the last seven days

**Comment by WillRebel** [comment]
Text changes have been made
