### ISSUE TITLE
Classes are red, green, blue --what does this mean?

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#47]
It might suggest that classes are weak or strong, as the same color coding is used in other places to suggest that. We should just choose a single color for all classes when loggin in to the teacher tools.

Unless we want to make red indicate that the students are not performing very well, as opposed to green.

**Comment by FrankSylvia** [comment]
The colors are randomly generated.  They have no meaning.

**Comment by IvonArroyo** [comment]
Correct, we need to give a single neural color to all of them, like green.

**Comment by FrankSylvia** [comment]
How about Green for active, Red for Archived

**Comment by IvonArroyo** [comment]
Sounds good. Go ahead!  --Ivon
------
Ivon Arroyo              http://alt.wpi.edu
Associate Professor
College of Education and College of Computer Science
University of Massachusetts Amherst
Amherst, MA 01002
