### ISSUE TITLE
New approach to Student Username Creation and maintenance

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#48]
CREATE STUDENT ID:

** Not evident what she has to do in each of those boxes. Create Student ID should be 'create usernames'     'Download usernames'

When create username opens up, not clear what should be written in each box:
"Stem (beginning) of user name"
"Password for the class"
"Number of usernames to create"

-----
'CloseClose' in message during user creation

* After username is entered, create users after trimming spaces
* Create users  should add a ‘-‘ with the number .

Remember your password for the student users  is 'mountview'. 
You can always also login with password '1587' (classID)

**Comment by IvonArroyo** [comment]
We now agreed that we are adding the classID to the username (before the '-' dash and the 1,2,3, etc.)  to guarantee that the user is unique.

**Comment by FrankSylvia** [comment]
I think the dash should be between the user part and the generated part, otherwise if the user's text ends with a number, e.g.  Grd74132-01  vs.  Grd7-413201.  Please comment...

**Comment by IvonArroyo** [comment]
Fix the download usernames.
