### ISSUE TITLE
Teacher tools: manage problem sets: accordion V doesn't open

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#5]
Screen Shot 2019-09-09 at 5 40 34 PM
<img width="1278" alt="issue_5" src="https://user-images.githubusercontent.com/46008380/66714928-25af6700-ed8b-11e9-9982-3215df5a5a3f.png">

Teacher tools: manage problem sets: accordion for "multiplication/division of fractions" (or is it alwats for the last topic in the list?) doesn't open to reveal the problems for that topic.

To test this, you may look at this class, or create a class with "Multiplication/.Division of Fractions" as part of the topics list.

**Comment by FrankSylvia** [comment]
Released to QA

**Comment by IvonArroyo** [comment]
This still doesn't work on the new development server release.
Check teacher: paula with pwd: corsico

and chose class: AA - 6th Grade -Section B (banana)

Try to open the first topics in the list. The only one that I was able to open was the last one.

--Ivon

**Comment by FrankSylvia** [comment]
Tested in Production. Works fine.
