### ISSUE TITLE
Assignment of problems to TOPICS upon MathSpring startup

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#50]
SET UP / REMOVE TOPICS THAT ARE NOT IN THE LEARNING PROGRESSIONS LIST.  OR SKIP THE PROBPROBGROUP ALTOGETHER.

UPDATE THE TOPICS OF THE PROBLEMS THAT ARE READY, SO THAT EVERY PROBLEM IS ASSIGNED TO A TOPIC IN THIS LIST.

**Comment by IvonArroyo** [comment]
This is related to Ankit's new script upon MathSpring startup. Once that the script runs, all of this should be solved.
