### ISSUE TITLE
Teacher Tools request - username generation

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#523]
When creating a class roster/student IDs, one chooses a Username Prefix and the Number of usernames to be created.

The code that generates the usernames has been changed to add the class number after the prefix before the student number.
This makes the username too long and complicated for young children. Please remove the class number in the usernames.
If I choose 'sample' as a prefix, I want the usernames to be sample01, sample02, sample03 etc. 
If I choose 'Math' as a prefix, I want the usernames to be Math01, Math02, Math03 etc..
This is how it has always been until recently.

I modified the requested format to be sample-01, sample-02.  Teachers often create prefixes with a trailing number as the last character. It can get confusing unless there is a delimiter between the prefix and the assigned number.

See image
![Screen Shot 2021-09-25 at 2 55 21 PM](https://user-images.githubusercontent.com/6811862/134783148-36561503-7caf-4241-8f2b-cb107588198e.png)

**Comment by WillRebel** [comment]
I also noticed this issue, and it seems like a bigger issue since the class counts as a password for the users.

**Comment by FrankSylvia** [comment]
R2 - add userPrefix validation to the create class function

**Comment by FrankSylvia** [comment]
This needs to be tested.
