### ISSUE TITLE
Teacher Tools - Mastery Bar

### ISSUE THREAD

**Issue by dallessio** [center-for-knowledge-communication/mathspring#524]
Please look at the Mastery Bar code, I believe that it is not correct.

See image.
10/12 problems solved correctly with flowers on the topic plant but only 10% mastery:
<img width="1440" alt="Screen Shot 2021-09-25 at 3 37 50 PM" src="https://user-images.githubusercontent.com/6811862/134784269-62c7ca40-e5f1-4f37-86fb-f4cb16dc2049.png">

**Comment by FrankSylvia** [comment]
Same as issue #555.  Closing
