### ISSUE TITLE
Class Cloning Issue

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#58]
Replicate a class. It is not clear what it does. It should say somewhere: What does it do?  This option replicates a class to create a new section of it. It doesn't bring existing students over, but it bring problem sets and any other settings.
 
The BUG is that The class name and the section have to be unique.
However, it demands that both the class name and the section be unique, when cloning a class.

Try cloning a class with the same name and see what happens, it fails and doesn't even give an error.

Once it gave me an exception:

Type Exception Report
Message Request processing failed; nested exception is java.lang.NullPointerException
Description The server encountered an unexpected condition that prevented it from fulfilling the request.

**Comment by FrankSylvia** [comment]
Class cloning has been removed as a feature.
