### ISSUE TITLE
Make sure updateMastery does not update the mastery when the problem gets SKIPPED

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#584]
Make sure updateMastery does not update the mastery when the problem gets SKIPPED.
If the student does not answer, the mastery should not get updated ever.

--Ivon

**Comment by FrankSylvia** [comment]
see Issue #555

**Comment by IvonArroyo** [comment]
I have the feeling that the mastery gets screwed up when students go to the Progress page a lot to see how their mastery bar changes. Could you please test this?

**Comment by FrankSylvia** [comment]
Hi Ivon,

I did look into this and found a flaw in the algorithm.  I made a
correction and I think that problem has been resolved.

That's not to say that the algorithm is absolutely correct.  if you have
other reports of abnormalities, I'd like to clear them up.

Frank
