### ISSUE TITLE
Cabin or Comic Sans MS or Trebuchet for problems

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#6]
The font of the problems is just incredibly boring for kids.

Could we change the default font in which HTML problems are rendered in MathSpring to one of there that are more round, and child-friendly? Would it always work in Chrome?

Cabin or Comic Sans MS or Trebuchet

It would just need to be about the same size as what we have, so that the problems that already exist and were created don't take more space than before.

**Comment by FrankSylvia** [comment]
Released to QA

**Comment by IvonArroyo** [comment]
This issue is ready to be closed, I don't know how you close an issue?

**Comment by ankitrgupta1** [comment]
reopened as it is yet to go to prod. No action is needed as of now.

**Comment by FrankSylvia** [comment]
Looks good.
