### ISSUE TITLE
Short Answer Evaluation: Remove all characters that are not numbers

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#67]
There are issues when Mathspring evaluates a correct or incorrect answer and the math problem is Short Answer. We think it would help a lot if, before comparing the user input and one of the possible candidate answers, MathSpring does the following:

Remove all characters that are not numbers, including spaces, from both student input answer and candidate correct answer with the following exceptions:

2. If the problem is in english, remove all characters from answer except: /  .  ^ (slash and dot and caret), then compare
3. If the problem is in spanish, remove  remove all characters from answer except: /  ,  ^ (slash and comma and caret)

**Comment by FrankSylvia** [comment]
See issue #158 for solution to this issue
