### ISSUE TITLE
Need a Report for Student x MathQuestion as a matrix 

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#7]
Teachers have asked for a report that is a matrix, where each row is a student and each column is a question.

Whenever a student has seen a question, we need a check or a minus (similar to the tiles in the SPP coding) where we can see how students have really done on a single question.

If the student has not seen the question, we should leave it blank for the time being. In the future we should make an estimation of whether the student would answer it correctly or not.
------------------------
All students in all classes? Sorted by class?
What does SPP stand for?
------------------------
This is another report for the class. It involves only the students in the class that the report is running for only.

This would be another report in the "Class Report Card", just like "Class Summary Per Common Core" for instance.

**Comment by FrankSylvia** [comment]
Released to QA

**Comment by IvonArroyo** [comment]
Is this done? We need the accordions to organize the problems of this report in 5.MD, 6.RP and such.

**Comment by FrankSylvia** [comment]
This is done using an input box. It will show all problems that match the
entered number.

**Comment by FrankSylvia** [comment]
This is a duplicate of 13.

**Comment by FrankSylvia** [comment]
Closing because it is a duplicate.
