### ISSUE TITLE
Security/Privacy Issue when downloading data for a classID?

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#74]
When you download the data for a class, potentially you can change the classID and download the data for another class.

Should we re-request the teacher's username and password?

--Ivon

**Comment by FrankSylvia** [comment]
This issue was expanded to protect both the class Id and the teacher Id from being modified on the url line.  Neither will appear on the url now.  This information is now maintained insession variables which are not accessible by the user.
