### ISSUE TITLE
Teacher Tools: Class Summary Per Problem Effort BAR Chart

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#75]
This chart gets larger every time you click on it.

The second time, and the third time, each time gets larger, and hovering generates an awful buggy behavior.

**Comment by IvonArroyo** [comment]
Also, hovering over the STATE of a student in the detail per student, SOF, NOTR, SHINT, ETC. works only if you don't scroll down.
The moment you scroll down it stops working or is off-set vertically.

**Comment by FrankSylvia** [comment]
I have verified that this issue is resolved.
