### ISSUE TITLE
Teacher Reports: Opening/Closing a report by clicking

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#8]
It is not very intuitive that you have to click on the link of a report again, in order to close it.
Can we come up with a more intuitive solution?

**Comment by FrankSylvia** [comment]
Released to QA in from Issue #7 branch.

**Comment by IvonArroyo** [comment]
This looks good, we can close this issue.  --ivon

**Comment by ankitrgupta1** [comment]
reopened as it is yet to go to prod. No action needed as of now.
