### ISSUE TITLE
Enable Flash button and message

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#9]
I believe the GLOSSARY button should be changed to 'Enable Flash', as the glossary itself is useless.

Also, because when flash is disabled, the HTML content scrolls up, there could be a hidden message under the text corresponding to the problem numbers, answers, etc.:

1794:3NF1_FlashRemake1
SHINT-SKIP-SKIP
Answer: b

That says in large font:

Click 'Enable Flash Player' to see the problems correctly.

**Comment by FrankSylvia** [comment]
Release to QA in ms-branch-14.  Bundled togther for convenience.

**Comment by IvonArroyo** [comment]
This one is ready to be closed.

**Comment by ankitrgupta1** [comment]
reopened as it is yet to be moved to prod

**Comment by FrankSylvia** [comment]
Tested in Production. Works fine.
